[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Sundstr√∂m Valter <mail@valter.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
